### ISSUE TITLE
[Twee] Extending the Twee format syntax.

### ISSUE THREAD

**Issue by tmedwards** [iftechfoundation/twine-specs#1]
There's been talk of extending the Twee format to allow for additional properties to be recorded—e.g. notably the story map coordinates in both Twine 1 & 2—since, at least, as far back as Twine 1.4 was still in development.

Let's discuss what extensions we'd like to see and, naturally, what syntax changes would be necessary to accommodate them.

----

- [x] Format name: *Twee v3*.
- [x] File extensions: `.tw`, `.twee`.
- [x] 100% compatibility with Twee v1 not required.
- [x] Retain the readability of Twee v1 as much as possible.
- [x] Encode the story and passage metadata as JSON.  The story metadata should be pretty-printed—i.e., line-broken and indented.  Passage metadata must be inline.  Metadata decoding errors should be non-fatal warnings—i.e., discard the metadata and attempt to continue processing.
- [x] Story metadata attributes (current):
  - [x] `ifdb`: (string, required) Maps to `<tw-storydata ifid>`.
  - [x] `format`: (string, optional) Maps to `<tw-storydata format>`.
  - [x] `format-version`: (string, optional) Maps to `<tw-storydata format-version>`.
  - [x] `start`: (string, optional) Maps to `<tw-passagedata name>` of the node whose `pid` matches `<tw-storydata startnode>`.
  - [x] `tag-colors`: (object of tag(string):color(string) pairs, optional) Indirectly maps to `<tw-tag>` nodes.
    - [x] tag:color pairs: (string:string, optional) Maps to `<tw-tag name>`:`<tw-tag color>`.
  - [x] `zoom`: (decimal, optional) Maps to `<tw-storydata zoom>`.
- [x] Passage metadata attributes (current):
  - [x] `position`: (string, optional) Comma separated passage icon positional coordinates—e.g., `600,400`.
  - [x] `size`: (string, optional) Comma separated passage icon width and height—e.g., `100,200`.
- [x] Passage header must be a single line and is composed of:
  - [x] Double colon start token (`::`), which must start the line.
  - [x] Name, which must directly follow the start token.
  - [x] (optional) Inline tag block, which must directly follow the name.
  - [x] (optional) Inline JSON metadata, which must directly follow either the tag block or, if the tag block is omitted, the name.
- [x] Compiler passages:
  - [x] `StoryTitle`: The project's name.  Maps to `<tw-storydata name>`.
  - [x] `Start`: The default starting passage.  May be overridden by the story metadata or compiler command.
  - [x] `StoryData`: The story metadata passage.  Must not be published to `<tw-storydata>`—i.e., the metadata should exist in one place.
- [x] Compiler tags:
  - [x] `script`: Signifies that the passage contents are JavaScript code.  Maps to the `<script type="text/twine-javascript">` node.
  - [x] `stylesheet`: Signifies that the passage content are CSS style rules.  Maps to the `<style type="text/twine-css">` node.
- [x] Within passage headers, passage and tag names must escape the optional tag and metadata block opening/closing metacharacters—i.e., `[`, `]`, `{`, `}`.
  - [x] Encoding: The escapement mechanism is to prefix the escaped characters with a backslash—i.e., `\`.  To avoid ambiguity, non-escape backslashes must also be escaped via the same mechanism—i.e., `foo\bar` yields `foo\\bar`.
  - [x] Decoding: To make decoding more robust, any escaped character within a chunk of encoded text yields the character minus the backslash—e.g., `\q` yields `q`.
- [x] Author-use area.

**NOTES:** The above task list is not meant to be absolute.  There are probably additional items that I'm not thinking of at the moment that should be on the list.

**Comment by videlais** [comment]
This repo is now public.

**Comment by tmedwards** [comment]
I have prerelease builds of Tweego v2 (v2.0.0-alpha.1) available if anyone wants to test it out—in general, or specifically its ability to properly parse Twee v3.  Pinging me on Discord would probably be the easiest way to get a build—though I could upload requests to Dropbox if necessary.

**Comment by tmedwards** [comment]
Bumped the Twee v3 specification to full release.
